# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Profile"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 20

[[main]]
  name = "Datasets"
  url = "#posts"
  weight = 30

[[main]]
  name = "Curation"
  url = "#posts"
  weight = 40

[[main]]
  name = "Courses"
  url = "#projects"
  weight = 50

[[main]]
  name = "Current"
  url = "#projects"
  weight = 60

[[main]]
  name = "<div class='website'>Website</div>"
  url = "https://www.jtmartelli.com/"
  weight = 70

[[main]]
  name = "&#128196;"
  url = "files/cv.pdf"
  weight = 80

#[[main]]
  #name = "Contact"
  #url = "#contact"
  #weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
